name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/Jellyfin.Plugin.PlaylistMaker/Jellyfin.Plugin.PlaylistMaker.csproj

      - name: Build
        run: dotnet build src/Jellyfin.Plugin.PlaylistMaker/Jellyfin.Plugin.PlaylistMaker.csproj --configuration Release --no-restore

      - name: Publish artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Jellyfin.Plugin.PlaylistMaker
          path: src/Jellyfin.Plugin.PlaylistMaker/bin/Release/net8.0/Jellyfin.Plugin.PlaylistMaker.dll
          if-no-files-found: error
